// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzzetjxjojptlmczxsco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16emV0anhqb2pwdGxtY3p4c2NvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NzU3MjQsImV4cCI6MjA2NDM1MTcyNH0.GvlT93Ti7qUY3ojorRmx2iAuC5rJvtzvefurLLSqntM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);